### ISSUE TITLE
To-do List App: Morning Review 20.06.2023

### ISSUE THREAD

**Issue by rmiyoyo** [mahdinoori2000/to-do-list#8]
Hello @mahdinoori2000 , great work so far! 
- [ ] Kindly consider adding an edit button in the list items, maybe next to the delete icon to make it easy for a user to know that they can edit items.
- [ ] As mentioned by @lily4178993, adding a new task to the list unticks the tasks that are already completed 🙏 
- [ ] @lily4178993 also mentioned an issue about your indexes starting at 1 instead of zero

**Comment by Sonikak004** [comment]
### Hi @mahdinoori2000, 👋 

you've done a great job, working on the project the styling is really impressive. You just have to work on one thing and you are good to go 👍 

- [x] Instead of using div's like below you can use semantic tags like header,nav.
https://github.com/mahdinoori2000/to-do-list/blob/80251f591b60f59cee317c13ec49aa8e38d6d079/src/index.html#L10-L16
